# Generated by Django 3.2.3 on 2021-06-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('ubdatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugestied', to='loginAuth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bookedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='loginAuth.user')),
                ('bookedWith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookedAt', to='loginAuth.user')),
            ],
        ),
        migrations.CreateModel(
            name='dayTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('startAt', models.DateTimeField()),
                ('endAt', models.DateTimeField()),
                ('freeTeachers', models.ManyToManyField(null=True, related_name='freeAt', to='loginAuth.User')),
            ],
        ),
    ]
