# Generated by Django 3.2.3 on 2021-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAuth', '0007_auto_20210606_1322'),
        ('waselApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytimeslot',
            name='freeTeachers',
            field=models.ManyToManyField(related_name='freeAt', to='loginAuth.User'),
        ),
    ]
