# Generated by Django 3.2.3 on 2021-06-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='0598321456', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='privilage',
            field=models.IntegerField(choices=[(9, 9), (8, 8), (7, 7), (1, 1), (0, 0)], default=9),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'm'), ('f', 'f')], default='m', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deleted', 'deleted'), ('inactive', 'inactive'), ('Suspended', 'Suspended')], default='active', max_length=25),
        ),
    ]
