# Generated by Django 3.2.3 on 2021-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAuth', '0002_auto_20210602_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default='old data field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='raters',
            field=models.IntegerField(null=True),
        ),
    ]
