# Generated by Django 3.2.3 on 2021-06-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAuth', '0003_auto_20210602_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sex',
            new_name='gender',
        ),
    ]
