# Generated by Django 3.2.3 on 2021-06-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAuth', '0004_rename_sex_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(max_length=254, null=True, upload_to='uploads/%Y%m%d'),
        ),
    ]
