# Generated by Django 3.2.3 on 2021-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAuth', '0005_auto_20210604_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('physics', 'physics'), ('chemistry', 'chemistry'), ('english', 'english'), ('mathematics', 'mathematics'), ('arabic', 'arabic'), ('biology', 'biology'), ('art', 'art'), ('music', 'music'), ('history', 'history')], default='english', max_length=25),
            preserve_default=False,
        ),
    ]
