# Generated by Django 3.2.3 on 2021-06-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAuth', '0007_auto_20210606_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('Ramallah', 'Ramallah'), ('Hebron', 'Hebron'), ('Nablus', 'Nablus'), ('Jenin', 'Jenin'), ('Bethlehem', 'Bethlehem')], max_length=35, null=True),
        ),
    ]
